language: php

php: 
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  -hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit

notifications:
  email:
    recipients:
      - turbo124@gmail.com
    on_success: change
    on_failure: change
